/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricscore;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Abrar
 */
public class criccric2 extends javax.swing.JFrame {

    /**
     * Creates new form criccric2
     */
    public criccric2() {
        initComponents();
    }
       ArrayList<String> arr1 = new ArrayList<String>();
            public String OVer1;
            public int overint1;  
            public String Runn1;
            public int runint1;
            public String Xtra1;
            public int xtraint1;
            public String Wicket1;
            public int wicketint1;
            public int Ball1;
            public int ballint1;
            //public boolean flag1 = false;
            public int GameRun1 = 0;
            public int totalover1 = 0;
            public int totalball1 =0;
            public int sstriker1run = 0;
            public int sstriker2run = 0;
            public boolean sstriker1 = true;
            public boolean sstriker2 = false;
            
            public String sstr = new String();
            public String sstr1 = new String();
            public String sstr3 = new String();
            public int j=0;
            public int wc1 = 0;
            public int xt1 = 0;
            public boolean sstrikerr1 = true;
            public int sstrikerr1run = 0;
            public String sstriker3 = "C";
            public boolean sstrikerr3 = false;
            public int sstrikerr3run = -1;
            public boolean entry3 = true;
            public String sstriker5 = "E";
            public boolean sstrikerr5 = false;
            public int sstrikerr5run = -1;
            public boolean entry5 = true;
            public String sstriker7 = "G";
            public boolean sstrikerr7 = false;
            public int sstrikerr7run = -1;
            public boolean entry7 = true;
            public String sstriker9 = "I";
            public boolean sstrikerr9 = false;
            public int sstrikerr9run = -1;
            public boolean entry9 = true;
            public String sstriker11 = "K";
            public int sstrikerr11run = -1;
            public boolean sstrikerr11 = false;
            public boolean entry11 = true;
            
            boolean flag1 = false;    
            public boolean sstrikerr2 = true;
            public int sstrikerr2run = 0;
            public String sstriker4 = "D";
            public int sstrikerr4run = -1;
            public boolean sstrikerr4 = false;
            public boolean entry4 = true;
            public String sstriker6 = "F";
            public int sstrikerr6run = -1;
            public boolean sstrikerr6 = false;
            public boolean entry6 = true;
            public String sstriker8 = "H";
            public int sstrikerr8run = -1;
            public boolean sstrikerr8 = false;
            public boolean entry8 = true;
            public String sstriker10 = "J";
            public int sstrikerr10run = -1;
            public boolean sstrikerr10 = false;
            public boolean entry10 = true;
            
            public boolean isout1 = true;
            public boolean XTRA1 = true;
            public int xcpRun1 = 0;
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Over = new javax.swing.JLabel();
        over = new javax.swing.JTextField();
        Balls = new javax.swing.JLabel();
        Run = new javax.swing.JLabel();
        run = new javax.swing.JTextField();
        run0 = new javax.swing.JButton();
        Run1 = new javax.swing.JButton();
        Run2 = new javax.swing.JButton();
        Run3 = new javax.swing.JButton();
        Run4 = new javax.swing.JButton();
        Run6 = new javax.swing.JButton();
        Extras = new javax.swing.JLabel();
        xtras = new javax.swing.JTextField();
        xtr0 = new javax.swing.JButton();
        xtr1 = new javax.swing.JButton();
        xtr2 = new javax.swing.JButton();
        xtr3 = new javax.swing.JButton();
        xtr4 = new javax.swing.JButton();
        wicket = new javax.swing.JTextField();
        Wickets = new javax.swing.JLabel();
        Out = new javax.swing.JRadioButton();
        Nout = new javax.swing.JRadioButton();
        genarate = new javax.swing.JButton();
        Comboover = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        ballss1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        Over.setFont(new java.awt.Font("Meiryo UI", 3, 11)); // NOI18N
        Over.setText("Over");
        jPanel1.add(Over);
        Over.setBounds(10, 20, 28, 15);

        over.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overActionPerformed(evt);
            }
        });
        jPanel1.add(over);
        over.setBounds(130, 10, 50, 30);

        Balls.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Balls.setText("Balls");
        jPanel1.add(Balls);
        Balls.setBounds(286, 24, 27, 17);

        Run.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Run.setText("Run");
        jPanel1.add(Run);
        Run.setBounds(10, 62, 22, 17);

        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        jPanel1.add(run);
        run.setBounds(70, 60, 60, 30);

        run0.setText("0");
        run0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run0ActionPerformed(evt);
            }
        });
        jPanel1.add(run0);
        run0.setBounds(170, 60, 39, 23);

        Run1.setText("1");
        Run1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run1ActionPerformed(evt);
            }
        });
        jPanel1.add(Run1);
        Run1.setBounds(220, 60, 39, 23);

        Run2.setText("2");
        Run2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run2ActionPerformed(evt);
            }
        });
        jPanel1.add(Run2);
        Run2.setBounds(270, 60, 39, 23);

        Run3.setText("3");
        Run3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run3ActionPerformed(evt);
            }
        });
        jPanel1.add(Run3);
        Run3.setBounds(320, 60, 39, 23);

        Run4.setText("4");
        Run4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run4ActionPerformed(evt);
            }
        });
        jPanel1.add(Run4);
        Run4.setBounds(370, 60, 39, 23);

        Run6.setText("6");
        Run6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run6ActionPerformed(evt);
            }
        });
        jPanel1.add(Run6);
        Run6.setBounds(420, 60, 39, 23);

        Extras.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Extras.setText("Extras");
        jPanel1.add(Extras);
        Extras.setBounds(10, 103, 37, 17);

        xtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtrasActionPerformed(evt);
            }
        });
        jPanel1.add(xtras);
        xtras.setBounds(70, 100, 60, 30);

        xtr0.setText("0");
        xtr0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr0ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr0);
        xtr0.setBounds(170, 100, 39, 23);

        xtr1.setText("1");
        xtr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr1ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr1);
        xtr1.setBounds(220, 100, 39, 23);

        xtr2.setText("2");
        xtr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr2ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr2);
        xtr2.setBounds(270, 100, 39, 23);

        xtr3.setText("3");
        xtr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr3ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr3);
        xtr3.setBounds(320, 100, 39, 23);

        xtr4.setBackground(new java.awt.Color(204, 204, 204));
        xtr4.setText("4");
        xtr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr4ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr4);
        xtr4.setBounds(370, 100, 39, 23);

        wicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wicketActionPerformed(evt);
            }
        });
        jPanel1.add(wicket);
        wicket.setBounds(70, 150, 60, 30);

        Wickets.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Wickets.setText("Wickets");
        jPanel1.add(Wickets);
        Wickets.setBounds(10, 153, 46, 17);

        Out.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Out.setText("Out");
        Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutActionPerformed(evt);
            }
        });
        jPanel1.add(Out);
        Out.setBounds(200, 150, 54, 25);

        Nout.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Nout.setText("Not out");
        Nout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoutActionPerformed(evt);
            }
        });
        jPanel1.add(Nout);
        Nout.setBounds(270, 150, 69, 25);

        genarate.setText("Genarate");
        genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateActionPerformed(evt);
            }
        });
        jPanel1.add(genarate);
        genarate.setBounds(360, 150, 100, 23);

        Comboover.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5" }));
        Comboover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombooverActionPerformed(evt);
            }
        });
        jPanel1.add(Comboover);
        Comboover.setBounds(60, 10, 60, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 240);

        ballss1.setText("yes");
        ballss1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballss1ActionPerformed(evt);
            }
        });
        jPanel1.add(ballss1);
        ballss1.setBounds(320, 20, 81, 23);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_overActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_runActionPerformed

    private void run0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run0ActionPerformed
        // TODO add your handling code here:
        sstr =  run0.getText();
        run.setText(sstr);
    }//GEN-LAST:event_run0ActionPerformed

    private void Run1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run1ActionPerformed
        // TODO add your handling code here:
        sstr =  Run1.getText();
        run.setText(sstr);
    }//GEN-LAST:event_Run1ActionPerformed

    private void Run2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run2ActionPerformed
        // TODO add your handling code here:
        sstr = Run2.getText();
        run.setText(sstr);
    }//GEN-LAST:event_Run2ActionPerformed

    private void Run3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run3ActionPerformed
        // TODO add your handling code here:
        sstr =  Run3.getText();
        run.setText(sstr);
    }//GEN-LAST:event_Run3ActionPerformed

    private void Run4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run4ActionPerformed
        sstr =  Run4.getText();
        run.setText(sstr);
        // TODO add your handling code here:
    }//GEN-LAST:event_Run4ActionPerformed

    private void Run6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run6ActionPerformed
        // TODO add your handling code here:
        sstr =  Run6.getText();
        run.setText(sstr);
    }//GEN-LAST:event_Run6ActionPerformed

    private void xtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtrasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_xtrasActionPerformed

    private void xtr0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr0ActionPerformed
        // TODO add your handling code here:
        // str1 = xtr0.getText();
        xtras.setText("0");
    }//GEN-LAST:event_xtr0ActionPerformed

    private void xtr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr1ActionPerformed
        // TODO add your handling code here:
        sstr1 = xtr1.getText();
        xtras.setText(sstr1);

    }//GEN-LAST:event_xtr1ActionPerformed

    private void xtr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr2ActionPerformed
        // TODO add your handling code here:
        sstr1 = xtr2.getText();
        xtras.setText(sstr1);
    }//GEN-LAST:event_xtr2ActionPerformed

    private void xtr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr3ActionPerformed
        // TODO add your handling code here:
        sstr1 = xtr3.getText();
        xtras.setText(sstr1);
    }//GEN-LAST:event_xtr3ActionPerformed

    private void xtr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr4ActionPerformed
        // TODO add your handling code here:
        sstr1 = xtr4.getText();
        xtras.setText(sstr1);
    }//GEN-LAST:event_xtr4ActionPerformed

    private void wicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wicketActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_wicketActionPerformed

    private void OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutActionPerformed
        // TODO add your handling code here:
        if(Out.isSelected()){
            wicket.setText("1");
            Nout.setSelected(false);
        }

    }//GEN-LAST:event_OutActionPerformed

    private void NoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoutActionPerformed
        // TODO add your handling code here:
        if(Nout.isSelected()){
            wicket.setText("0");
            Out.setSelected(false);
        }
    }//GEN-LAST:event_NoutActionPerformed

    private void genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateActionPerformed
        // TODO add your handling code here:
        //1st innings
        try{

            String OVer1 = over.getText();
            int overint1 = Integer.parseInt(OVer1);

            String Run1 = run.getText();
            int runint1 = Integer.parseInt(Run1);

            String Xtra1 = xtras.getText();
            int xtraint1 = Integer.parseInt(Xtra1);

            if(xtraint1!=0){
                xt1 = 1;
            }
            else {
                xt1 = 0;
            }

            String Wicket1 = wicket.getText();
            int wicketint1 = Integer.parseInt(Wicket1);

            if(wicketint1==1 && xtraint1 ==0){
                wc1 = wc1  + 1;
            }
             if(wicketint1==11){  
                    System.exit(0);
                }
           

            String wkt1;
            wkt1 = Integer.toString(wc1);

            if(overint1<0 || runint1<0 || xtraint1<0 || wicketint1<0 || ballint1<0 ){
                JOptionPane.showMessageDialog(null, "Sorry The Input Is Not Valid", "ERROR",2);
            }
            else{
                if(!flag1)
                {
                    Visualizer2 objct1 = new Visualizer2();
                    objct1.setVisible(true);
                    flag1 = true;
                }

              if(wicketint1 == 1 && xtraint1!=1){
                   GameRun1 = GameRun1;
               }
                else if(xtraint1 ==1){
                    
                GameRun1 = runint1 + xtraint1 + GameRun1;
                String OutputRun = Integer.toString(GameRun1);
                Visualizer.Ruun.setText(OutputRun);
                }
                 else if ( (runint1>=1 && runint1<=6) && wicketint1!=1){
                    GameRun1 = runint1+GameRun1;
                    String OutputRun = Integer.toString(GameRun1);
                    Visualizer2.Ruun1.setText(OutputRun);
                }
                   
                criccric one=new criccric();
                int targetrun = Integer.parseInt(criccric.GetTarget());
                Visualizer2.target.setText(criccric.GetTarget());
                
                
                totalball1 = totalball1 + Ball1 - xt1;
                int over1 = totalball1/6;
                String OutputOver1 = Integer.toString(over1);
                Visualizer2.ovr2.setText(OutputOver1);
                int ball1 = totalball1%6;
                String OutputBall1 = Integer.toString(ball1);
                Visualizer2.ball2.setText(OutputBall1);
                //arr1.add(Run1);
                
                 if ( wicketint1!=1 && xtraint1 ==0 ){
                      arr1.add(Run1);
                Visualizer2.thisover1.setText(Visualizer2.thisover1.getText() + arr1.get(j) +" ");
                j++;
                 }
                 else if (xtraint1 !=0)   
                 {    //arr1.add("Xt");                               
                     Visualizer2.thisover1.setText(Visualizer2.thisover1.getText() + Xtra1 +" ");
                j++;}
                 else if (wc1 ==1)
                 {  //arr1.add("W");
                     Visualizer2.thisover1.setText(Visualizer2.thisover1.getText() + "W" +" ");
                j++;}

                if((totalball1%6)==0)
                {
                    Visualizer2.thisover1.setText(null);
                }

                
               
                if(wc1>=1 && wc1 <=9 && wicketint1 == 1){
                  if(sstriker1)
                  {
                    
                    Visualizer2.Wickts1.setText(wkt1); 
                    Visualizer2.striker1.setText(sstriker3);
                    if(sstrikerr3run == -1 ){
                        sstrikerr3run = 0;
                        sstrikerr3 = true;
                        sstriker1 = false;
                        String OutputstRun3 = Integer.toString(sstrikerr3run);
                        Visualizer2.strikerrun1.setText(OutputstRun3);    
                    }     
                    }
                    else if(sstrikerr3){
                   
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.striker1.setText(sstriker5);
                    if(sstrikerr5run == -1 ){
                      sstrikerr5run = 0;
                      sstrikerr5 = true;
                      sstrikerr3 = false;
                      String OutputtRun5 = Integer.toString(sstrikerr5run);
                    Visualizer2.strikerrun1.setText(OutputtRun5);
                    }
                    
                    }
                    else if( sstrikerr5){
                    
                    Visualizer2.Wickts1.setText(wkt1); 
                    Visualizer2.striker1.setText(sstriker7);
                    if(sstrikerr7run == -1 ){
                        sstrikerr7run = 0;
                        sstrikerr7 = true;
                        sstrikerr5 = false;
                         String OutputtRun7 = Integer.toString(sstrikerr7run);
                    Visualizer2.strikerrun1.setText(OutputtRun7);
                    }
                
                    }
                    
                    else if(sstrikerr7){
                    
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.striker1.setText(sstriker9);
                    if(sstrikerr9run == -1 ){
                        sstrikerr9run = 0;
                        sstrikerr9 = true;
                        sstrikerr7 = false;
                        String OutputtRun9 = Integer.toString(sstrikerr9run);
                    Visualizer2.strikerrun1.setText(OutputtRun9);
                    }   
                    }
                    
                    else if( sstrikerr9){
                    
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.striker1.setText(sstriker11);
                    if(sstrikerr11run == -1 ){
                        sstrikerr11run = 0;
                        sstrikerr11 = true;
                        sstrikerr9 = false;
                        String OutputtRun11 = Integer.toString(sstrikerr11run);
                    Visualizer2.strikerrun1.setText(OutputtRun11);
                    }
                   
                    
                }  
                  else if( sstrikerr2){
                    
                    
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.nonstriker1.setText(sstriker4);
                    if(sstrikerr4run == -1 ){
                        sstrikerr4run = 0;
                          sstriker2 = false;
                          sstrikerr4 = true;
                         String OutputtRun4 = Integer.toString(sstrikerr4run);
                    Visualizer2.nonstrikerrun1.setText(OutputtRun4);
                    
                    }
                    
                }
                else if( sstrikerr4){
                   
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.nonstriker1.setText(sstriker6);
                    if(sstrikerr6run == -1 ){sstrikerr6run = 0;
                        sstrikerr6 = true;
                         sstrikerr4 = false;
                    String OutputtRun6 = Integer.toString(sstrikerr6run);
                    Visualizer2.nonstrikerrun1.setText(OutputtRun6);
                    }
                    
                   
                    
                }
                else if(sstrikerr6){
                    
                    Visualizer2.Wickts1.setText(wkt1);  
                    Visualizer2.nonstriker1.setText(sstriker8);
                    if(sstrikerr8run == -1 ){
                        sstrikerr8run = 0;
                        sstrikerr8 = true;
                         sstrikerr6 = false;
                         String OutputtRun8 = Integer.toString(sstrikerr7run);
                    Visualizer2.nonstrikerrun1.setText(OutputtRun8);
                    }
                   
                    
                }
                else if(sstrikerr8){
                    
                    Visualizer2.Wickts1.setText(wkt1); 
                    Visualizer2.nonstriker1.setText(sstriker10);
                    if(sstrikerr10run == -1 ){sstrikerr10run = 0;
                        sstrikerr10 = true;
                         sstrikerr8 = false;
                         String OutputtRun10 = Integer.toString(sstrikerr10run);
                    Visualizer2.nonstrikerrun1.setText(OutputtRun10);
                    }
                  
                    
                     }
                   }
                     else if(wc1 == 10){
                    Visualizer2.Wickts1.setText(wkt1);
                 }
                
                if((runint1 == 1 || runint1 == 3) && (sstriker1 || sstrikerr3 || sstrikerr5
                                                    || sstrikerr7|| sstrikerr9 || sstrikerr11)){
                    String OutputRun1="0";
                    go:{
                    if(sstriker1){ sstriker1run = sstriker1run+runint1;
                    OutputRun1 = Integer.toString(sstriker1run);
                    }
                    else if(sstrikerr3){
                        if(!entry3){sstrikerr3run = sstrikerr3run+runint1;
                             OutputRun1 = Integer.toString(sstrikerr3run);}
                        else {entry3 = false;
                        break go;}
                    }
                    else if(sstrikerr5){
                        if(!entry5){sstrikerr5run = sstrikerr5run+runint1;
                        OutputRun1 = Integer.toString(sstrikerr5run);}
                        else {entry5 = false;
                            break go;}
                    }
                    else if(sstrikerr7){
                        if(!entry7){sstrikerr7run = sstrikerr7run+runint1;
                        OutputRun1 = Integer.toString(sstrikerr7run);}
                        else {entry7 = false;
                            break go;}
                    }
                    else if(sstrikerr9){
                        
                        if(!entry9){sstrikerr9run = sstrikerr9run+runint1;
                        OutputRun1 = Integer.toString(sstrikerr9run);}
                        else { entry9 = false;
                                break go;}
                    }
                    else if(sstrikerr11){
                        if(!entry11){sstrikerr11run = sstrikerr11run+runint1;
                        OutputRun1 = Integer.toString(sstrikerr11run); }
                        else {entry11 =false;
                                break go;}
                    }
                    Visualizer2.strikerrun1.setText(OutputRun1);
                    sstriker1 = false;
                    sstrikerr3 = false;
                    sstrikerr5 = false;
                    sstrikerr7 = false;
                    sstrikerr9 = false;
                    sstrikerr11 = false;
                    
                    if(wc1 == 2 && sstriker2) sstrikerr4 = true;
                    else if(wc1 == 4&& sstrikerr4)sstrikerr6 = true;
                    else if(wc1 == 6&& sstrikerr6)sstrikerr8 = true;
                    else if(wc1 == 8&& sstrikerr8) sstrikerr10 = true;
                    else sstriker2= true;}
                    
                }
                else if((runint1 == 1 || runint1 == 3) &&( sstriker2 || sstrikerr4||
                                                        sstrikerr6 || sstrikerr8 || sstrikerr10) ){
                   
                     String OutputRun2="0";
                     go : {
                    if(sstriker2){sstriker2run = sstriker2run+runint1;
                    OutputRun2 = Integer.toString(sstriker2run);
                    }
                    else if(sstrikerr4){
                        if(!entry4){sstrikerr4run = sstrikerr4run+runint1;
                         OutputRun2 = Integer.toString(sstrikerr4run);}
                        else{ entry4 = false;
                            break go;}
                    }
                    else if(sstrikerr6){
                        if(!entry6){sstrikerr6run = sstrikerr6run+runint1;
                         OutputRun2 = Integer.toString(sstrikerr6run);}
                        else {entry6 = false;
                                break go;}
                    }
                    else if(sstrikerr8){
                        if(!entry8){sstrikerr8run = sstrikerr8run+runint1;
                         OutputRun2 = Integer.toString(sstrikerr8run);}
                        else {entry8 = false;
                            break go;}
                    }
                    else if(sstrikerr10){
                        if(!entry10){sstrikerr10run = sstrikerr10run+runint1;
                         OutputRun2 = Integer.toString(sstrikerr10run);}
                        else {entry10 = false;
                                break go;}
                    }
                    
                    Visualizer2.nonstrikerrun1.setText(OutputRun2);
                    sstriker2 = false;
                    sstrikerr4 = false;
                    sstrikerr6 = false;
                    sstrikerr8 = false;
                    sstrikerr10 = false;
                     
                    if(wc1 == 1 && sstriker1) sstrikerr3 = true;
                    else if(wc1 == 3 && sstrikerr3) sstrikerr5 = true;
                    else if(wc1 == 5 && sstrikerr5)sstrikerr9 = true;
                    else if(wc1 == 9 && sstrikerr9)sstrikerr11 = true;
                    else sstriker1= true;}
                    
                }
                else if((runint1 == 2 || runint1 == 4 || runint1 == 6) && (sstriker1 || sstrikerr3 || sstrikerr5
                                                    || sstrikerr7|| sstrikerr9 || sstrikerr11) ){
                    
                    String OutputRun3="0";
                    go:{
                    if(sstriker1){ sstriker1run = sstriker1run+runint1;
                    OutputRun3 = Integer.toString(sstriker1run);
                    }
                    else if(sstrikerr3){
                        if(!entry3){sstrikerr3run = sstrikerr3run+runint1;
                             OutputRun3 = Integer.toString(sstrikerr3run);}
                        else {entry3 = false;
                                break go;}
                    }
                    else if(sstrikerr5){
                        if(!entry5){sstrikerr5run = sstrikerr5run+runint1;
                        OutputRun3 = Integer.toString(sstrikerr5run);}
                        else {entry5 = false;
                                break go;}
                    }
                    else if(sstrikerr7){
                        if(!entry7){sstrikerr7run = sstrikerr7run+runint1;
                        OutputRun3 = Integer.toString(sstrikerr7run);}
                        else {entry7 = false;
                            break go;}
                    }
                    else if(sstrikerr9){
                        
                        if(!entry9){sstrikerr9run = sstrikerr9run+runint1;
                        OutputRun3 = Integer.toString(sstrikerr9run);}
                        else {entry9 = false;
                            break go;}
                    }
                    else if(sstrikerr11){
                        if(!entry11){sstrikerr11run = sstrikerr11run+runint1;
                        OutputRun3 = Integer.toString(sstrikerr11run); }
                        else {entry11 =false;
                        break go;
                        }
                    }
                    Visualizer2.strikerrun1.setText(OutputRun3);
                    sstriker1 = false;
                    sstrikerr3 = false;
                    sstrikerr5 = false;
                    sstrikerr7 = false;
                    sstrikerr9 = false;
                    sstrikerr11 = false;
                    
                    if(wc1 == 2 && sstriker2) sstrikerr4 = true;
                    else if(wc1 == 4&& sstrikerr4) sstrikerr6 = true;
                    else if(wc1 == 6&& sstrikerr6) sstrikerr8 = true;
                    else if(wc1 == 8&& sstrikerr8) sstrikerr10 = true;
                    else sstriker2= true;}
                }
                else if((runint1 == 2 || runint1 == 4 || runint1 == 6 ) && ( sstriker2 || sstrikerr4||
                                                        sstrikerr6 || sstrikerr8 || sstrikerr10) ){
                    
                    String OutputRun4="0";
                    go:{
                   
                    if(sstriker2){sstriker2run = sstriker2run+runint1;
                    OutputRun4 = Integer.toString(sstriker2run);
                    }
                    else if(sstrikerr4){
                        if(!entry4){sstrikerr4run = sstrikerr4run+runint1;
                         OutputRun4 = Integer.toString(sstrikerr4run);}
                        else{ entry4 = false;
                            break go;}
                    }
                    else if(sstrikerr6){
                        if(!entry6){sstrikerr6run = sstrikerr6run+runint1;
                         OutputRun4 = Integer.toString(sstrikerr6run);}
                        else {entry6 = false;
                                break go;}
                    }
                    else if(sstrikerr8){
                        if(!entry8){sstrikerr8run = sstrikerr8run+runint1;
                         OutputRun4 = Integer.toString(sstrikerr8run);}
                        else {entry8 = false;
                            break go;}
                    }
                    else if(sstrikerr10){
                        if(!entry10){sstrikerr10run = sstrikerr10run+runint1;
                         OutputRun4 = Integer.toString(sstrikerr10run);}
                        else {entry10 = false;
                                break go;}
                    }
                    Visualizer2.nonstrikerrun1.setText(OutputRun4);
                    sstriker2 = false;
                    sstrikerr4 = false;
                    sstrikerr6 = false;
                    sstrikerr8 = false;
                    sstrikerr10 = false;
                    
                   if(wc1 == 1 && sstriker1) sstrikerr3 = true;
                    else if(wc1 == 3 && sstrikerr3) sstrikerr5 = true;
                    else if(wc1 == 5 && sstrikerr5) sstrikerr7 = true;
                    else if(wc1 == 7 && sstrikerr7) sstrikerr9 = true;
                    else if(wc1== 9 && sstrikerr9)sstrikerr11 = true;
                    else sstriker1= true;}
                }
                
                
                if((totalball1%6) == 0 &&  (sstriker2 || sstrikerr4||
                                                        sstrikerr6 || sstrikerr8 || sstrikerr10)){
                    sstriker1 = false;
                    sstrikerr3 = false;
                    sstrikerr5 = false;
                    sstrikerr7 = false;
                    sstrikerr9 = false;
                    sstrikerr11 = false;
                    
                    if(wc1 == 2 && sstriker2) sstrikerr4 = true;
                    else if(wc1 == 4&& sstrikerr4) sstrikerr6 = true;
                    else if(wc1 == 6&& sstrikerr6) sstrikerr8 = true;
                    else if(wc1 == 8&& sstrikerr8) sstrikerr10 = true;
                    else sstriker2= true;
                }
                else if((totalball1%6) == 0 && (sstriker1 || sstrikerr3 || sstrikerr5
                                                    || sstrikerr7|| sstrikerr9 || sstrikerr11)){
                
                    sstriker2 = false;
                    sstrikerr4 = false;
                    sstrikerr6 = false;
                    sstrikerr8 = false;
                    sstrikerr10 = false;
                    
                    if(wc1 == 1 && sstriker1) sstrikerr3 = true;
                    else if(wc1 == 3 && sstrikerr3) sstrikerr5 = true;
                    else if(wc1 == 5 && sstrikerr5) sstrikerr7 = true;
                    else if(wc1 == 7 && sstrikerr7) sstrikerr9 = true;
                    else if(wc1 == 9 && sstrikerr9)sstrikerr11 = true;
                    else sstriker1= true;
                }
                    if(wc1>=1) Visualizer.Wickts.setText(wkt1);
                    else  Visualizer.Wickts.setText("0");
                
                        if(wc1>=1) Visualizer2.Wickts1.setText(wkt1);
                         else  Visualizer2.Wickts1.setText("0");
              
              
                    //GAMEOVER
              if(wc1==11 || GameRun1 >=targetrun || totalball1==(overint1*6) ){ 
                  
                  Gameover object = new Gameover();
                  object.setVisible(true);
                  
                   Visualizer2 objct1= new Visualizer2();
                   this.setVisible(false);
                   
               if ((targetrun-1)>GameRun1){
               
               Gameover.Result.setText("Team A won the match");
               }
               else if ((targetrun-1)<GameRun1){
               Gameover.Result.setText("Team B won the match");
               }
               else {
               Gameover.Result.setText("Match draw");}
            }
    
                
            }
            
          

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry The Input Is Not Valid", "ERROR", 2);
        }

    }//GEN-LAST:event_genarateActionPerformed

    private void CombooverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombooverActionPerformed

        if(Comboover.getSelectedItem().equals("2")){
            over.setText("2");
        }
        if(Comboover.getSelectedItem().equals("3")){
            over.setText("3");
        }
        if(Comboover.getSelectedItem().equals("4")){
            over.setText("4");
        }
        if(Comboover.getSelectedItem().equals("5")){
            over.setText("5");
        }

    }//GEN-LAST:event_CombooverActionPerformed

    private void ballss1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballss1ActionPerformed
        // TODO add your handling code here:
          if(ballss1.isSelected()){
            Ball1 = Ball1 +1;
        }
        else{
            Ball1 = Ball1;
        }
    }//GEN-LAST:event_ballss1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criccric2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criccric2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criccric2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criccric2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criccric2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balls;
    private javax.swing.JComboBox<String> Comboover;
    private javax.swing.JLabel Extras;
    public static javax.swing.JRadioButton Nout;
    public static javax.swing.JRadioButton Out;
    private javax.swing.JLabel Over;
    private javax.swing.JLabel Run;
    public static javax.swing.JButton Run1;
    private javax.swing.JButton Run2;
    private javax.swing.JButton Run3;
    private javax.swing.JButton Run4;
    private javax.swing.JButton Run6;
    private javax.swing.JLabel Wickets;
    public static javax.swing.JCheckBox ballss1;
    private javax.swing.JButton genarate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField over;
    public static javax.swing.JTextField run;
    private javax.swing.JButton run0;
    public static javax.swing.JTextField wicket;
    public static javax.swing.JButton xtr0;
    public static javax.swing.JButton xtr1;
    public static javax.swing.JButton xtr2;
    public static javax.swing.JButton xtr3;
    public static javax.swing.JButton xtr4;
    private javax.swing.JTextField xtras;
    // End of variables declaration//GEN-END:variables
}
