/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricscore;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class criccric extends javax.swing.JFrame {

    /**
     * Creates new form criccric
     */
    public criccric() {
        initComponents();
    }
            ArrayList<String> arr = new ArrayList<String>();
            public String OVer;
            public int overint;  
            public String Runn;
            public int runint;
            public String Xtra;
            public int xtraint;
            public String Wicket;
            public int wicketint;
            public int Ball;
            public int ballint;
            public boolean flag = false;
            public static int GameRun = 0;
            public int totalover = 0;
            public int totalball =0;
            public int striker1run = 0;
            public int striker2run = 0;
            public boolean striker1 = true;
            public boolean striker2 = false;
            
            public String str = new String();
            public String str1 = new String();
            public String str3 = new String();
            public int i=0;
            public int wc = 0;
            public int xt = 0;
            public boolean strikerr1 = true;
            public int strikerr1run = 0;
            public String striker3 = "C";
            public boolean strikerr3 = false;
            public boolean entry3 = true;
            public int strikerr3run = -1;
            public String striker5 = "E";
            public boolean strikerr5 = false;
            public boolean entry5 = true;
            public int strikerr5run = -1;
            public String striker7 = "G";
            public boolean strikerr7 = false;
            public boolean entry7 = true;
            public int strikerr7run = -1;
            public String striker9 = "I";
            public boolean strikerr9 = false;
            public boolean entry9 = true;
            public int strikerr9run = -1;
            public String striker11 = "K";
             public boolean strikerr11 = false;
             public boolean entry11 = true;
            public int strikerr11run = -1;
              
            public boolean strikerr2 = true;
            public int strikerr2run = 0;
            public String striker4 = "D";
            public int strikerr4run = -1;
            public boolean strikerr4 = false;
            public boolean entry4 = true;
            public String striker6 = "F";
            public int strikerr6run = -1;
            public boolean strikerr6 = false;
            public boolean entry6 = true;
            public String striker8 = "H";
            public int strikerr8run = -1;
            public boolean strikerr8 = false;
            public boolean entry8 = true;
            public String striker10 = "J";
            public int strikerr10run = -1;
            public boolean strikerr10 = false;
            public boolean entry10 = true;
            
            
            public boolean isout = true;
            public boolean XTRA = true;
            public int xcpRun = 0;
           /* public void close(){
                WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
                Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);      
            }*
            
    /**      
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        Over = new javax.swing.JLabel();
        over = new javax.swing.JTextField();
        Balls = new javax.swing.JLabel();
        Run = new javax.swing.JLabel();
        run = new javax.swing.JTextField();
        run0 = new javax.swing.JButton();
        Run1 = new javax.swing.JButton();
        Run2 = new javax.swing.JButton();
        Run3 = new javax.swing.JButton();
        Run4 = new javax.swing.JButton();
        Run6 = new javax.swing.JButton();
        Extras = new javax.swing.JLabel();
        xtras = new javax.swing.JTextField();
        xtr0 = new javax.swing.JButton();
        xtr1 = new javax.swing.JButton();
        xtr2 = new javax.swing.JButton();
        xtr3 = new javax.swing.JButton();
        xtr4 = new javax.swing.JButton();
        wicket = new javax.swing.JTextField();
        Wickets = new javax.swing.JLabel();
        Out = new javax.swing.JRadioButton();
        Nout = new javax.swing.JRadioButton();
        genarate = new javax.swing.JButton();
        Comboover = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        ballss = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server's Run Genarator");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        Over.setFont(new java.awt.Font("Meiryo UI", 3, 11)); // NOI18N
        Over.setText("Over");
        jPanel1.add(Over);
        Over.setBounds(10, 20, 28, 15);

        over.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overActionPerformed(evt);
            }
        });
        jPanel1.add(over);
        over.setBounds(130, 10, 50, 30);

        Balls.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Balls.setText("Balls");
        jPanel1.add(Balls);
        Balls.setBounds(286, 24, 27, 17);

        Run.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Run.setText("Run");
        jPanel1.add(Run);
        Run.setBounds(10, 62, 22, 17);

        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        jPanel1.add(run);
        run.setBounds(70, 60, 60, 30);

        run0.setText("0");
        run0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run0ActionPerformed(evt);
            }
        });
        jPanel1.add(run0);
        run0.setBounds(170, 60, 39, 23);

        Run1.setText("1");
        Run1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run1ActionPerformed(evt);
            }
        });
        jPanel1.add(Run1);
        Run1.setBounds(220, 60, 39, 23);

        Run2.setText("2");
        Run2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run2ActionPerformed(evt);
            }
        });
        jPanel1.add(Run2);
        Run2.setBounds(270, 60, 39, 23);

        Run3.setText("3");
        Run3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run3ActionPerformed(evt);
            }
        });
        jPanel1.add(Run3);
        Run3.setBounds(320, 60, 39, 23);

        Run4.setText("4");
        Run4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run4ActionPerformed(evt);
            }
        });
        jPanel1.add(Run4);
        Run4.setBounds(370, 60, 39, 23);

        Run6.setText("6");
        Run6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run6ActionPerformed(evt);
            }
        });
        jPanel1.add(Run6);
        Run6.setBounds(420, 60, 39, 23);

        Extras.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Extras.setText("Extras");
        jPanel1.add(Extras);
        Extras.setBounds(10, 103, 37, 17);

        xtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtrasActionPerformed(evt);
            }
        });
        jPanel1.add(xtras);
        xtras.setBounds(70, 100, 60, 30);

        xtr0.setText("0");
        xtr0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr0ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr0);
        xtr0.setBounds(170, 100, 39, 23);

        xtr1.setText("1");
        xtr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr1ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr1);
        xtr1.setBounds(220, 100, 39, 23);

        xtr2.setText("2");
        xtr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr2ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr2);
        xtr2.setBounds(270, 100, 39, 23);

        xtr3.setText("3");
        xtr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr3ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr3);
        xtr3.setBounds(320, 100, 39, 23);

        xtr4.setBackground(new java.awt.Color(204, 204, 204));
        xtr4.setText("4");
        xtr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtr4ActionPerformed(evt);
            }
        });
        jPanel1.add(xtr4);
        xtr4.setBounds(370, 100, 39, 23);

        wicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wicketActionPerformed(evt);
            }
        });
        jPanel1.add(wicket);
        wicket.setBounds(70, 150, 60, 30);

        Wickets.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Wickets.setText("Wickets");
        jPanel1.add(Wickets);
        Wickets.setBounds(10, 153, 46, 17);

        Out.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Out.setText("Out");
        Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutActionPerformed(evt);
            }
        });
        jPanel1.add(Out);
        Out.setBounds(200, 150, 54, 25);

        Nout.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        Nout.setText("Not out");
        Nout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoutActionPerformed(evt);
            }
        });
        jPanel1.add(Nout);
        Nout.setBounds(270, 150, 69, 25);

        genarate.setText("Genarate");
        genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateActionPerformed(evt);
            }
        });
        jPanel1.add(genarate);
        genarate.setBounds(360, 150, 100, 23);

        Comboover.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5" }));
        Comboover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombooverActionPerformed(evt);
            }
        });
        jPanel1.add(Comboover);
        Comboover.setBounds(60, 10, 60, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 220);

        ballss.setText("yes");
        ballss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballssActionPerformed(evt);
            }
        });
        jPanel1.add(ballss);
        ballss.setBounds(320, 20, 81, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\2.1 SD lab project\\Final & updated\\final_Cricscore 2\\86316.2.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overActionPerformed
        // TODO add your handling code here 
        
    }//GEN-LAST:event_overActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_runActionPerformed

    private void xtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtrasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_xtrasActionPerformed

    private void wicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wicketActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_wicketActionPerformed

    public static String GetTarget()
             { 
                 int trgt = GameRun+1;
                 String targetR = Integer.toString(trgt);
                 return targetR;
             }
    private void genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateActionPerformed
        // TODO add your handling code here:
        //1st innings
        try{
            
            String OVer = over.getText();
            int overint = Integer.parseInt(OVer);
            
            String Run = run.getText();
            int runint = Integer.parseInt(Run);
            
            String Xtra = xtras.getText();
            int xtraint = Integer.parseInt(Xtra);
            
            if(xtraint!= 0){
                xt = 1;
            }
            else {
                xt = 0;
            }
            
            String Wicket = wicket.getText();
            int wicketint = Integer.parseInt(Wicket);
            
            
            if(wicketint==1 && xtraint == 0){
            wc = wc + 1;
            }
            
           
            String wkt;
            wkt = Integer.toString(wc);

            if(overint<0 || runint<0 || xtraint<0 || wicketint<0 || ballint<0 ){
            JOptionPane.showMessageDialog(null, "Sorry The Input Is Not Valid", "ERROR",2);
            }   
            else{   
                if(!flag)
                {
                     Visualizer objct = new Visualizer();
                     objct.setVisible(true);  
                     flag = true;
                }
               if(wicketint == 1 && xtraint!=1 ){
                   GameRun = GameRun;
               }
                else if(xtraint ==1){
                GameRun = runint + xtraint + GameRun;
                String OutputRun = Integer.toString(GameRun);
                Visualizer.Ruun.setText(OutputRun);
                }
              
                else if ((runint>=1 && runint<=6) && wicketint!=1){
                    
                    GameRun = runint+GameRun;
                    String OutputRun = Integer.toString(GameRun);
                    Visualizer.Ruun.setText(OutputRun);
                }
   
               if((totalball%6)==0)
               {
                  Visualizer.thisover.setText(null); 
               }
                 
                totalball = totalball + Ball - xt;
                int over = totalball/6; 
                String OutputOver = Integer.toString(over);
                Visualizer.ovr1.setText(OutputOver);
                int ball = totalball%6;
                String OutputBall = Integer.toString(ball);
                Visualizer.ball1.setText(OutputBall);
                //arr.add(Run);
              
                
                
                if (wicketint!=1 && xtraint ==0 ){
                    arr.add(Run);
                Visualizer.thisover.setText(Visualizer.thisover.getText() + arr.get(i) +" ");
                i++;
                 }
                 else if (xtraint!=0 && wc!=1)
                 {
                     arr.add("Xt");
                     Visualizer.thisover.setText(Visualizer.thisover.getText() + Xtra +arr.get(i)+" ");
                i++;
                 }
                 else 
                 {
                     arr.add("W");
                     Visualizer.thisover.setText(Visualizer.thisover.getText() + arr.get(i) +" ");
                i++;
                 }
                
           
               if(wc>=1 && wc <=9 && wicketint == 1){
                  if(striker1)
                  {
                    
                    Visualizer.Wickts.setText(wkt); 
                    Visualizer.striker.setText(striker3);
                    if(strikerr3run == -1){
                        strikerr3run = 0;
                        strikerr3 = true;
                        striker1 = false;
                        String OutputstRun3 = Integer.toString(strikerr3run);
                        Visualizer.strikerrun.setText(OutputstRun3);    
                    }     
                    }
                    else if(strikerr3){
                   
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.striker.setText(striker5);
                    if(strikerr5run == -1 ){
                      strikerr5run = 0;
                      strikerr5 = true;
                      strikerr3 = false;
                      String OutputtRun5 = Integer.toString(strikerr5run);
                    Visualizer.strikerrun.setText(OutputtRun5);
                    }
                    
                    }
                    else if( strikerr5){
                    
                    Visualizer.Wickts.setText(wkt); 
                    Visualizer.striker.setText(striker7);
                    if(strikerr7run == -1 ){
                        strikerr7run = 0;
                        strikerr7 = true;
                        strikerr5 = false;
                        String OutputtRun7 = Integer.toString(strikerr7run);
                    Visualizer.strikerrun.setText(OutputtRun7);
                    }
                
                    }
                    
                    else if(strikerr7){
                    
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.striker.setText(striker9);
                    if(strikerr9run == -1 ){
                        strikerr9run = 0;
                        strikerr9 = true;
                        strikerr7 = false;
                        String OutputtRun9 = Integer.toString(strikerr9run);
                    Visualizer.strikerrun.setText(OutputtRun9);
                    }   
                    }
                    
                    else if(strikerr9){
                    
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.striker.setText(striker11);
                    if(strikerr11run == -1 ){
                        strikerr11run = 0;
                        strikerr11 = true;
                        strikerr9 = false;
                        String OutputtRun11 = Integer.toString(strikerr11run);
                    Visualizer.strikerrun.setText(OutputtRun11);
                    }
                   
                    
                }  
                  else if(strikerr2){
                    
                    
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.nonstriker.setText(striker4);
                    if(strikerr4run == -1 ){
                        strikerr4run = 0;
                        striker2 = false;
                        strikerr4 = true;
                         String OutputtRun4 = Integer.toString(strikerr4run);
                    Visualizer.nonstrikerrun.setText(OutputtRun4);
                    
                    }
                    
                }
                else if(strikerr4){
                   
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.nonstriker.setText(striker6);
                    if(strikerr6run == -1 ){strikerr6run = 0;
                        strikerr6 = true;
                         strikerr4 = false;
                    String OutputtRun6 = Integer.toString(strikerr6run);
                    Visualizer.nonstrikerrun.setText(OutputtRun6);
                    }
                    
                   
                    
                }
                else if(strikerr6){
                    
                    Visualizer.Wickts.setText(wkt);  
                    Visualizer.nonstriker.setText(striker8);
                    if(strikerr8run == -1 ){
                        strikerr8run = 0;
                        strikerr8 = true;
                         strikerr6 = false;
                         String OutputtRun8 = Integer.toString(strikerr7run);
                    Visualizer.nonstrikerrun.setText(OutputtRun8);
                    }
                   
                    
                }
                else if(strikerr8){
                    
                    Visualizer.Wickts.setText(wkt); 
                    Visualizer.nonstriker.setText(striker10);
                    if(strikerr10run == -1 ){strikerr10run = 0;
                        strikerr10 = true;
                         strikerr8 = false;
                         String OutputtRun10 = Integer.toString(strikerr10run);
                    Visualizer.nonstrikerrun.setText(OutputtRun10);
                    }
                  
                    
                }
                }
                 else if(wc == 10){
                    Visualizer.Wickts.setText(wkt); 
                 }
                                 
            } 
                  
                if((runint == 1 || runint == 3) && (striker1 || strikerr3 || strikerr5
                                                    || strikerr7|| strikerr9 || strikerr11)){
                    String OutputRun1="0";
                    go:{
                    if(striker1){ striker1run = striker1run+runint;
                    OutputRun1 = Integer.toString(striker1run);
                    }
                    else if(strikerr3){
                        if(!entry3){strikerr3run = strikerr3run+runint;
                             OutputRun1 = Integer.toString(strikerr3run);}
                        else {entry3 = false;
                        break go;}
                    }
                    else if(strikerr5){
                        if(!entry5){strikerr5run = strikerr5run+runint;
                        OutputRun1 = Integer.toString(strikerr5run);}
                        else {entry5 = false;
                            break go;}
                    }
                    else if(strikerr7){
                        if(!entry7){strikerr7run = strikerr7run+runint;
                        OutputRun1 = Integer.toString(strikerr7run);}
                        else {entry7 = false;
                            break go;}
                    }
                    else if(strikerr9){
                        
                        if(!entry9){strikerr9run = strikerr9run+runint;
                        OutputRun1 = Integer.toString(strikerr9run);}
                        else { entry9 = false;
                                break go;}
                    }
                    else if(strikerr11){
                        if(!entry11){strikerr11run = strikerr11run+runint;
                        OutputRun1 = Integer.toString(strikerr11run); }
                        else {entry11 = false;
                                break go;}
                    }
                    Visualizer.strikerrun.setText(OutputRun1);
                    striker1 = false;
                    strikerr3 = false;
                    strikerr5 = false;
                    strikerr7 = false;
                    strikerr9 = false;
                    strikerr11 = false;
                    
                    if(wc == 2 && striker2) strikerr4 = true;
                    else if(wc == 4 && strikerr4) strikerr6 = true;
                    else if(wc == 6 && strikerr6) strikerr8 = true;
                    else if(wc == 8 && strikerr8) strikerr10 = true;
                    else striker2= true;
                    }
                    
                }
                else if((runint == 1 || runint == 3) &&( striker2 || strikerr4||
                                                        strikerr6 || strikerr8 || strikerr10) ){
                   
                     String OutputRun2="0";
                     go : {
                    if(striker2){striker2run = striker2run+runint;
                    OutputRun2 = Integer.toString(striker2run);
                    }
                    else if(strikerr4){
                        if(!entry4){strikerr4run = strikerr4run+runint;
                         OutputRun2 = Integer.toString(strikerr4run);}
                        else{ entry4 = false;
                            break go;}
                    }
                    else if(strikerr6){
                        if(!entry6){strikerr6run = strikerr6run+runint;
                         OutputRun2 = Integer.toString(strikerr6run);}
                        else {entry6 = false;
                                break go;}
                    }
                    else if(strikerr8){
                        if(!entry8){strikerr8run = strikerr8run+runint;
                         OutputRun2 = Integer.toString(strikerr8run);}
                        else {entry8 = false;
                            break go;}
                    }
                    else if(strikerr10){
                        if(!entry10){strikerr10run = strikerr10run+runint;
                         OutputRun2 = Integer.toString(strikerr10run);}
                        else {entry10 = false;
                                break go;}
                    }
                    
                    Visualizer.nonstrikerrun.setText(OutputRun2);
                    striker2 = false;
                    strikerr4 = false;
                    strikerr6 = false;
                    strikerr8 = false;
                    strikerr10 = false;
                     
                    if(wc == 1 && striker1) strikerr3 = true;
                    else if(wc == 3 && strikerr3) strikerr5 = true;
                    else if(wc == 5 && strikerr5) strikerr7 = true;
                    else if(wc == 7 && strikerr7) strikerr9 = true;
                    else if(wc == 9 && strikerr9)strikerr11 = true;
                    else striker1= true;}
                    
                }
                else if((runint == 2 || runint == 4 || runint == 6) && (striker1 || strikerr3 || strikerr5
                                                    || strikerr7|| strikerr9 || strikerr11) ){
                    
                    String OutputRun3="0";
                    go:{
                    if(striker1){ striker1run = striker1run+runint;
                    OutputRun3 = Integer.toString(striker1run);
                    }
                    else if(strikerr3){
                        if(!entry3){strikerr3run = strikerr3run+runint;
                             OutputRun3 = Integer.toString(strikerr3run);}
                        else {entry3 = false;
                                break go;}
                    }
                    else if(strikerr5){
                        if(!entry5){strikerr5run = strikerr5run+runint;
                        OutputRun3 = Integer.toString(strikerr5run);}
                        else {entry5 = false;
                                break go;}
                    }
                    else if(strikerr7){
                        if(!entry7){strikerr7run = strikerr7run+runint;
                        OutputRun3 = Integer.toString(strikerr7run);}
                        else {entry7 = false;
                            break go;}
                    }
                    else if(strikerr9){
                        
                        if(!entry9){strikerr9run = strikerr9run+runint;
                        OutputRun3 = Integer.toString(strikerr9run);}
                        else {entry9 = false;
                            break go;}
                    }
                    else if(strikerr11){
                        if(!entry11){strikerr11run = strikerr11run+runint;
                        OutputRun3 = Integer.toString(strikerr11run); }
                        else {entry11 =false;
                        break go;
                        }
                    }
                    Visualizer.strikerrun.setText(OutputRun3);
                    striker1 = false;
                    strikerr3 = false;
                    strikerr5 = false;
                    strikerr7 = false;
                    strikerr9 = false;
                    strikerr11 = false;
                    
                    if(wc == 2 && striker2) strikerr4 = true;
                    else if(wc == 4&& strikerr4) strikerr6 = true;
                    else if(wc == 6&& strikerr6) strikerr8 = true;
                    else if(wc == 8&& strikerr8) strikerr10 = true;
                    else striker2= true;}
                }
                else if((runint == 2 || runint == 4 || runint == 6 ) && ( striker2 || strikerr4||
                                                        strikerr6 || strikerr8 || strikerr10) ){
                    
                    String OutputRun4="0";
                    go:{
                   
                    if(striker2){striker2run = striker2run+runint;
                    OutputRun4 = Integer.toString(striker2run);
                    }
                    else if(strikerr4){
                        if(!entry4){strikerr4run = strikerr4run+runint;
                         OutputRun4 = Integer.toString(strikerr4run);}
                        else{ entry4 = false;
                            break go;}
                    }
                    else if(strikerr6){
                        if(!entry6){strikerr6run = strikerr6run+runint;
                         OutputRun4 = Integer.toString(strikerr6run);}
                        else {entry6 = false;
                                break go;}
                    }
                    else if(strikerr8){
                        if(!entry8){strikerr8run = strikerr8run+runint;
                         OutputRun4 = Integer.toString(strikerr8run);}
                        else {entry8 = false;
                            break go;}
                    }
                    else if(strikerr10){
                        if(!entry10){strikerr10run = strikerr10run+runint;
                         OutputRun4 = Integer.toString(strikerr10run);}
                        else {entry10 = false;
                                break go;}
                    }
                    Visualizer.nonstrikerrun.setText(OutputRun4);
                    striker2 = false;
                    strikerr4 = false;
                    strikerr6 = false;
                    strikerr8 = false;
                    strikerr10 = false;
                    
                   if(wc == 1 && striker1) strikerr3 = true;
                    else if(wc == 3 && strikerr3) strikerr5 = true;
                    else if(wc == 5 && strikerr5) strikerr7 = true;
                    else if(wc == 7 && strikerr7) strikerr9 = true;
                    else if(wc == 9 && strikerr9)strikerr11 = true;
                    else striker1= true;}
                }
                
                
                 else if((totalball%6) == 0 &&  (striker2 || strikerr4||
                                                        strikerr6 || strikerr8 || strikerr10)){
                    striker1 = false;
                    strikerr3 = false;
                    strikerr5 = false;
                    strikerr7 = false;
                    strikerr9 = false;
                    strikerr11 = false;
                    
                    if(wc == 2 && striker2) strikerr4 = true;
                    else if(wc == 4&& strikerr4) strikerr6 = true;
                    else if(wc == 6&& strikerr6) strikerr8 = true;
                    else if(wc == 8&& strikerr8) strikerr10 = true;
                    else striker2= true;
                }
                
                if((totalball%6) == 0 && (striker1 || strikerr3 || strikerr5
                                                    || strikerr7|| strikerr9 || strikerr11)){
                    striker2 = false;
                    strikerr4 = false;
                    strikerr6 = false;
                    strikerr8 = false;
                    strikerr10 = false;
                    
                    if(wc == 1 && striker1) strikerr3 = true;
                    else if(wc == 3 && strikerr3) strikerr5 = true;
                    else if(wc == 5 && strikerr5) strikerr7 = true;
                    else if(wc == 7 && strikerr7) strikerr9 = true;
                    else if(wc == 9 && strikerr9)strikerr11 = true;
                    else striker1= true;
                }
                    if(wc>=1) Visualizer.Wickts.setText(wkt);
                    else  Visualizer.Wickts.setText("0");
              
                
                
               
             //2nd innings
            if(wc==11){ 
            int trgt = GameRun+1;
            String targetR = Integer.toString(trgt);
            Visualizer objct = new Visualizer();
             this.setVisible(false);  
             criccric2 objct2 = new criccric2();
             objct2.setVisible(true);
             Visualizer.ovr1.setText(null);
            
             Visualizer.Ruun.setText(null);
             Visualizer.Wickts.setText(null);
             Visualizer.ball1.setText(null);
             Visualizer.strikerrun.setText(null);
             Visualizer.nonstrikerrun.setText(null);
             Visualizer.thisover.setText(null);   
               
             Visualizer2 objct3 = new Visualizer2();
              
            
             Visualizer2.ovr2.setText(null);
             Visualizer2.target.setText(targetR);
             Visualizer2.Ruun1.setText(null);
             Visualizer2.Wickts1.setText(null);
             Visualizer2.ball2.setText(null);
             Visualizer2.strikerrun1.setText(null);
             Visualizer2.nonstrikerrun1.setText(null);
             Visualizer2.thisover1.setText(null);
            }
            else if(totalball==(overint*6)){
                
             int trgt = GameRun+1;
            String targetR = Integer.toString(trgt);
            Visualizer objct = new Visualizer();
             this.setVisible(false);  
             criccric2 objct2 = new criccric2();
             objct2.setVisible(true);
             Visualizer.ovr1.setText(null);
            
             Visualizer.Ruun.setText(null);
             Visualizer.Wickts.setText(null);
             Visualizer.ball1.setText(null);
             Visualizer.strikerrun.setText(null);
             Visualizer.nonstrikerrun.setText(null);
             Visualizer.thisover.setText(null);   
                
             Visualizer2 objct3 = new Visualizer2();
               
             Visualizer2.ovr2.setText(null);
             Visualizer2.Ruun1.setText(null);
             Visualizer2.Wickts1.setText(null);
             Visualizer2.ball2.setText(null);
             Visualizer2.strikerrun1.setText(null);
             Visualizer2.nonstrikerrun1.setText(null);
             Visualizer2.thisover1.setText(null);
            }
            
            
               
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Sorry The Input Is Not Valid", "ERROR", 2);
              }
      
    }//GEN-LAST:event_genarateActionPerformed
        
    
    private void Run1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run1ActionPerformed
        // TODO add your handling code here:
         str =  Run1.getText();
         run.setText(str);

    }//GEN-LAST:event_Run1ActionPerformed

    private void Run2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run2ActionPerformed
        // TODO add your handling code here:
         str = Run2.getText();
         run.setText(str);
    }//GEN-LAST:event_Run2ActionPerformed

    private void Run3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run3ActionPerformed
        // TODO add your handling code here:
         str =  Run3.getText();
        run.setText(str);
    }//GEN-LAST:event_Run3ActionPerformed

    private void Run4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run4ActionPerformed
        str =  Run4.getText();
        run.setText(str);
        // TODO add your handling code here:
    }//GEN-LAST:event_Run4ActionPerformed

    private void Run6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run6ActionPerformed
        // TODO add your handling code here:
        str =  Run6.getText();
        run.setText(str);
    }//GEN-LAST:event_Run6ActionPerformed

    private void OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutActionPerformed
        // TODO add your handling code here:
        if(Out.isSelected()){
           // wicket.setText(true);
            wicket.setText("1");
            Nout.setSelected(false);
        }
        
    }//GEN-LAST:event_OutActionPerformed

    private void NoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoutActionPerformed
        // TODO add your handling code here:
        if(Nout.isSelected()){
            wicket.setText("0");
            Out.setSelected(false);
        }
    }//GEN-LAST:event_NoutActionPerformed

    private void xtr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr1ActionPerformed
        // TODO add your handling code here:
        str1 = xtr1.getText();
        xtras.setText(str1);
        
    }//GEN-LAST:event_xtr1ActionPerformed

    private void xtr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr2ActionPerformed
        // TODO add your handling code here:
        str1 = xtr2.getText();
        xtras.setText(str1); 
    }//GEN-LAST:event_xtr2ActionPerformed

    private void xtr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr3ActionPerformed
        // TODO add your handling code here:
        str1 = xtr3.getText();
        xtras.setText(str1);
    }//GEN-LAST:event_xtr3ActionPerformed

    private void xtr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr4ActionPerformed
        // TODO add your handling code here:
        str1 = xtr4.getText();
        xtras.setText(str1);
    }//GEN-LAST:event_xtr4ActionPerformed

    private void xtr0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtr0ActionPerformed
        // TODO add your handling code here:
           // str1 = xtr0.getText();
           xtras.setText("0");
    }//GEN-LAST:event_xtr0ActionPerformed

    private void run0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run0ActionPerformed
        // TODO add your handling code here:
            str =  run0.getText();
            run.setText(str);   
    }//GEN-LAST:event_run0ActionPerformed

    private void CombooverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombooverActionPerformed
        
            if(Comboover.getSelectedItem().equals("2")){
                over.setText("2");
            }
            if(Comboover.getSelectedItem().equals("3")){
                over.setText("3");
            }
            if(Comboover.getSelectedItem().equals("4")){
                over.setText("4");
            }
            if(Comboover.getSelectedItem().equals("5")){
                over.setText("5");
            }
            
    }//GEN-LAST:event_CombooverActionPerformed

    private void ballssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballssActionPerformed
        // TODO add your handling code here:
        if(ballss.isSelected()){
        Ball = Ball +1;    
    }                                     
        else {
            Ball = Ball;
        }
    }//GEN-LAST:event_ballssActionPerformed
    

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criccric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criccric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criccric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criccric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criccric().setVisible(true);
                
                
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balls;
    private javax.swing.JComboBox<String> Comboover;
    private javax.swing.JLabel Extras;
    public static javax.swing.JRadioButton Nout;
    public static javax.swing.JRadioButton Out;
    private javax.swing.JLabel Over;
    private javax.swing.JLabel Run;
    public static javax.swing.JButton Run1;
    private javax.swing.JButton Run2;
    private javax.swing.JButton Run3;
    private javax.swing.JButton Run4;
    private javax.swing.JButton Run6;
    private javax.swing.JLabel Wickets;
    public static javax.swing.JCheckBox ballss;
    private javax.swing.JButton genarate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField over;
    public static javax.swing.JTextField run;
    private javax.swing.JButton run0;
    public static javax.swing.JTextField wicket;
    public static javax.swing.JButton xtr0;
    public static javax.swing.JButton xtr1;
    public static javax.swing.JButton xtr2;
    public static javax.swing.JButton xtr3;
    public static javax.swing.JButton xtr4;
    private javax.swing.JTextField xtras;
    // End of variables declaration//GEN-END:variables
}
