/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricscore;

/**
 *
 * @author User
 */
    

public class Visualizer extends javax.swing.JFrame {

    /**
     * Creates new form Visualizer
     */
 
    public Visualizer() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ruun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Wickts = new javax.swing.JTextField();
        ovr1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ball1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        striker = new javax.swing.JTextField();
        strikerrun = new javax.swing.JTextField();
        nonstriker = new javax.swing.JTextField();
        nonstrikerrun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thisover = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Score Visualizer");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Run");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 30, 30);

        Ruun.setBackground(new java.awt.Color(51, 0, 51));
        Ruun.setForeground(new java.awt.Color(255, 255, 204));
        Ruun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuunActionPerformed(evt);
            }
        });
        jPanel1.add(Ruun);
        Ruun.setBounds(120, 30, 39, 30);

        jLabel4.setText("/");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(164, 30, 10, 30);

        Wickts.setBackground(new java.awt.Color(51, 0, 51));
        Wickts.setForeground(new java.awt.Color(255, 255, 204));
        Wickts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WicktsActionPerformed(evt);
            }
        });
        jPanel1.add(Wickts);
        Wickts.setBounds(180, 30, 39, 30);

        ovr1.setBackground(new java.awt.Color(51, 0, 51));
        ovr1.setForeground(new java.awt.Color(255, 255, 204));
        ovr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovr1ActionPerformed(evt);
            }
        });
        jPanel1.add(ovr1);
        ovr1.setBounds(120, 70, 39, 30);

        jLabel2.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel2.setText(".");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 80, 4, 17);

        ball1.setBackground(new java.awt.Color(51, 0, 51));
        ball1.setForeground(new java.awt.Color(255, 255, 204));
        ball1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ball1ActionPerformed(evt);
            }
        });
        jPanel1.add(ball1);
        ball1.setBounds(180, 70, 39, 30);

        jLabel3.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Over");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 70, 30, 30);

        striker.setBackground(new java.awt.Color(0, 153, 153));
        striker.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        striker.setForeground(new java.awt.Color(255, 255, 204));
        striker.setText("A");
        jPanel1.add(striker);
        striker.setBounds(50, 120, 97, 30);

        strikerrun.setBackground(new java.awt.Color(51, 0, 51));
        strikerrun.setForeground(new java.awt.Color(255, 255, 204));
        strikerrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strikerrunActionPerformed(evt);
            }
        });
        jPanel1.add(strikerrun);
        strikerrun.setBounds(170, 120, 39, 30);

        nonstriker.setBackground(new java.awt.Color(0, 153, 153));
        nonstriker.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        nonstriker.setForeground(new java.awt.Color(255, 255, 204));
        nonstriker.setText("B");
        jPanel1.add(nonstriker);
        nonstriker.setBounds(50, 160, 97, 30);

        nonstrikerrun.setBackground(new java.awt.Color(51, 0, 51));
        nonstrikerrun.setForeground(new java.awt.Color(255, 255, 204));
        nonstrikerrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonstrikerrunActionPerformed(evt);
            }
        });
        jPanel1.add(nonstrikerrun);
        nonstrikerrun.setBounds(170, 160, 39, 30);

        jLabel5.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("THIS OVER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 200, 65, 20);

        thisover.setBackground(new java.awt.Color(51, 0, 51));
        thisover.setForeground(new java.awt.Color(255, 255, 204));
        thisover.setText(" ");
        thisover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thisoverActionPerformed(evt);
            }
        });
        jPanel1.add(thisover);
        thisover.setBounds(50, 230, 266, 40);

        jLabel6.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("1st  Innings");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 0, 90, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\2.1 SD lab project\\Final & updated\\final_Cricscore 2\\images.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1, 1, 430, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RuunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuunActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RuunActionPerformed

    private void WicktsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WicktsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WicktsActionPerformed

    private void ovr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovr1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ovr1ActionPerformed

    private void ball1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ball1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ball1ActionPerformed

    private void strikerrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strikerrunActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_strikerrunActionPerformed

    private void nonstrikerrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonstrikerrunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonstrikerrunActionPerformed

    private void thisoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thisoverActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_thisoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Ruun;
    public static javax.swing.JTextField Wickts;
    public static javax.swing.JTextField ball1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField nonstriker;
    public static javax.swing.JTextField nonstrikerrun;
    public static javax.swing.JTextField ovr1;
    public static javax.swing.JTextField striker;
    public static javax.swing.JTextField strikerrun;
    public static javax.swing.JTextField thisover;
    // End of variables declaration//GEN-END:variables

}
