/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricscore;

/**
 *
 * @author Abrar
 */
public class Visualizer2 extends javax.swing.JFrame {

    /**
     * Creates new form Visualizer2
     */
    public Visualizer2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ruun1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Wickts1 = new javax.swing.JTextField();
        ovr2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ball2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        striker1 = new javax.swing.JTextField();
        strikerrun1 = new javax.swing.JTextField();
        nonstriker1 = new javax.swing.JTextField();
        nonstrikerrun1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thisover1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        target = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Run");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(47, 39, 30, 30);

        Ruun1.setBackground(new java.awt.Color(51, 0, 51));
        Ruun1.setForeground(new java.awt.Color(255, 255, 204));
        Ruun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ruun1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ruun1);
        Ruun1.setBounds(159, 40, 39, 30);

        jLabel4.setText("/");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(202, 50, 4, 20);

        Wickts1.setBackground(new java.awt.Color(51, 0, 51));
        Wickts1.setForeground(new java.awt.Color(255, 255, 204));
        Wickts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wickts1ActionPerformed(evt);
            }
        });
        jPanel1.add(Wickts1);
        Wickts1.setBounds(210, 40, 39, 30);

        ovr2.setBackground(new java.awt.Color(51, 0, 51));
        ovr2.setForeground(new java.awt.Color(255, 255, 204));
        ovr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovr2ActionPerformed(evt);
            }
        });
        jPanel1.add(ovr2);
        ovr2.setBounds(159, 81, 39, 30);

        jLabel2.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel2.setText(".");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(202, 84, 4, 17);

        ball2.setBackground(new java.awt.Color(51, 0, 51));
        ball2.setForeground(new java.awt.Color(255, 255, 204));
        ball2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ball2ActionPerformed(evt);
            }
        });
        jPanel1.add(ball2);
        ball2.setBounds(210, 81, 39, 30);

        jLabel3.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Over");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(47, 81, 40, 30);

        striker1.setBackground(new java.awt.Color(0, 153, 153));
        striker1.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        striker1.setForeground(new java.awt.Color(255, 255, 204));
        striker1.setText("A1");
        jPanel1.add(striker1);
        striker1.setBounds(50, 130, 97, 30);

        strikerrun1.setBackground(new java.awt.Color(51, 0, 51));
        strikerrun1.setForeground(new java.awt.Color(255, 255, 204));
        strikerrun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strikerrun1ActionPerformed(evt);
            }
        });
        jPanel1.add(strikerrun1);
        strikerrun1.setBounds(170, 130, 77, 30);

        nonstriker1.setBackground(new java.awt.Color(0, 153, 153));
        nonstriker1.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        nonstriker1.setForeground(new java.awt.Color(255, 255, 204));
        nonstriker1.setText("B1");
        jPanel1.add(nonstriker1);
        nonstriker1.setBounds(50, 170, 97, 30);

        nonstrikerrun1.setBackground(new java.awt.Color(51, 0, 51));
        nonstrikerrun1.setForeground(new java.awt.Color(255, 255, 204));
        nonstrikerrun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonstrikerrun1ActionPerformed(evt);
            }
        });
        jPanel1.add(nonstrikerrun1);
        nonstrikerrun1.setBounds(170, 170, 77, 30);

        jLabel5.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("THIS OVER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 220, 65, 30);

        thisover1.setBackground(new java.awt.Color(51, 0, 51));
        thisover1.setForeground(new java.awt.Color(255, 255, 204));
        thisover1.setText(" ");
        thisover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thisover1ActionPerformed(evt);
            }
        });
        jPanel1.add(thisover1);
        thisover1.setBounds(50, 260, 266, 40);

        jLabel6.setBackground(new java.awt.Color(51, 0, 51));
        jLabel6.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("2nd Innings");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 10, 90, 30);

        jLabel7.setFont(new java.awt.Font("Meiryo", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Target");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 10, 41, 30);

        target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetActionPerformed(evt);
            }
        });
        jPanel1.add(target);
        target.setBounds(300, 10, 58, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("F:\\2.1 SD lab project\\Final & updated\\final_Cricscore 2\\images.jpg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 390, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ruun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ruun1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Ruun1ActionPerformed

    private void Wickts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wickts1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Wickts1ActionPerformed

    private void ovr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovr2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ovr2ActionPerformed

    private void ball2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ball2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ball2ActionPerformed

    private void strikerrun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strikerrun1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_strikerrun1ActionPerformed

    private void nonstrikerrun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonstrikerrun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonstrikerrun1ActionPerformed

    private void thisover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thisover1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_thisover1ActionPerformed

    private void targetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Ruun1;
    public static javax.swing.JTextField Wickts1;
    public static javax.swing.JTextField ball2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField nonstriker1;
    public static javax.swing.JTextField nonstrikerrun1;
    public static javax.swing.JTextField ovr2;
    public static javax.swing.JTextField striker1;
    public static javax.swing.JTextField strikerrun1;
    public static javax.swing.JTextField target;
    public static javax.swing.JTextField thisover1;
    // End of variables declaration//GEN-END:variables
}
